### ISSUE TITLE
create roadmap

### ISSUE THREAD

**Issue by matanshukry** [bennyz/feelings_bot#5]
Create ROADMAP.md

Possibly include:
- [] Instructions for local testing
- [] Creating cloud version of the bot
- [] add ci that will include formatting + go build (later on add tests to it)
